In [44]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.DataFrame(pd.read_csv("Student_Mental_health.csv"))
df

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [47]:
df.drop("Timestamp", axis=1, inplace=True)
df

,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...
96,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [48]:
df['What is your course?'].unique()

array(['Engineering', 'Islamic education', 'BIT', 'Laws', 'Mathemathics',
       'Pendidikan islam', 'BCS', 'Human Resources', 'Irkhs',
       'Psychology', 'KENMS', 'Accounting ', 'ENM', 'Marine science',
       'KOE', 'Banking Studies', 'Business Administration', 'Law',
       'KIRKHS', 'Usuluddin ', 'TAASL', 'Engine', 'ALA',
       'Biomedical science', 'koe', 'Kirkhs', 'BENL', 'Benl', 'IT', 'CTS',
       'engin', 'Econs', 'MHSC', 'Malcom', 'Kop', 'Human Sciences ',
       'Biotechnology', 'Communication ', 'Diploma Nursing',
       'Pendidikan Islam ', 'Radiography', 'psychology', 'Fiqh fatwa ',
       'DIPLOMA TESL', 'Koe', 'Fiqh', 'Islamic Education', 'Nursing ',
       'Pendidikan Islam'], dtype=object)

In [49]:
df.columns = ['Gender','Age','Course','Year','CGPA','Marital','Depression','Anxiety','Panic','Treatment']
df['Course'] = df['Course'].str.strip()
df['Year'] = df['Year'].str.extract('(\\d+)').astype(int)

In [50]:
course_clean_mapping = {
    'Engineering'           : 'Engineering',
    'Engine'                : 'Engineering',
    'engin'                 : 'Engineering',
    'KOE'                   : 'Engineering',
    'koe'                   : 'Engineering',
    'Koe'                   : 'Engineering',
    'BCS'                   : 'BCS',
    'BIT'                   : 'BIT',
    'IT'                    : 'BIT',
    'CTS'                   : 'BIT',
    'Biomedical science'    : 'Biomedical Science',
    'Biotechnology'         : 'Biotechnology',
    'Mathemathics'          : 'Mathematics',
    'Marine science'        : 'Marine Science',
    'Islamic education'     : 'Islamic Education',
    'Islamic Education'     : 'Islamic Education',
    'Pendidikan islam'      : 'Islamic Education',
    'Pendidikan Islam'      : 'Islamic Education',
    'Irkhs'                 : 'Islamic Education',
    'KIRKHS'                : 'Islamic Education',
    'Kirkhs'                : 'Islamic Education',
    'Fiqh fatwa'            : 'Islamic Education',
    'Fiqh'                  : 'Islamic Education',
    'Usuluddin'             : 'Islamic Education',
    'MHSC'                  : 'Islamic Education',
    'Malcom'                : 'Islamic Education',
    'BENL'                  : 'English Language',
    'Benl'                  : 'English Language',
    'TAASL'                 : 'English Language',
    'ALA'                   : 'English Language',
    'DIPLOMA TESL'          : 'English Language',
    'Human Resources'       : 'Human Sciences',
    'Human Sciences'        : 'Human Sciences',
    'Psychology'            : 'Psychology',
    'psychology'            : 'Psychology',
    'Laws'                  : 'Law',
    'Law'                   : 'Law',
    'Nursing'               : 'Nursing',
    'Diploma Nursing'       : 'Nursing',
    'Radiography'           : 'Radiography',
    'Communication'         : 'Communication',
    'Econs'                 : 'Economics',
    'ENM'                   : 'Economics',
    'KENMS'                 : 'Economics',
    'Business Administration': 'Business Administration',
    'Banking Studies'       : 'Banking Studies',
    'Accounting'            : 'Accounting',
    'Kop'                   : 'Other',
}

In [51]:
# ── Step 2: Mapping ke 3 rumpun final ────────────────────────────────────────
rumpun_mapping = {
    # STEM
    'Engineering'           : 'STEM',
    'BCS'                   : 'STEM',
    'BIT'                   : 'STEM',
    'Biomedical Science'    : 'STEM',
    'Biotechnology'         : 'STEM',
    'Mathematics'           : 'STEM',
    'Marine Science'        : 'STEM',
 
    # Social & Humanities (termasuk Islamic Education, Health, Language)
    'Islamic Education'     : 'Social & Humanities',
    'English Language'      : 'Social & Humanities',
    'Human Sciences'        : 'Social & Humanities',
    'Psychology'            : 'Social & Humanities',
    'Law'                   : 'Social & Humanities',
    'Nursing'               : 'Social & Humanities',
    'Radiography'           : 'Social & Humanities',
    'Communication'         : 'Social & Humanities',
 
    # Business & Economics
    'Economics'             : 'Business & Economics',
    'Business Administration': 'Business & Economics',
    'Banking Studies'       : 'Business & Economics',
    'Accounting'            : 'Business & Economics',
 
    # Other tetap Other (hanya 1 data, bisa di-drop saat modeling)
    'Other'                 : 'Other',
}

In [52]:
df['Course_clean'] = df['Course'].map(course_clean_mapping)
df['Course_group'] = df['Course_clean'].map(rumpun_mapping)

In [53]:
unmapped = df[df['Course_group'].isna()]['Course'].unique()
if len(unmapped) > 0:
    print("⚠️  UNMAPPED:", unmapped)
else:
    print("✅ Semua course berhasil dikelompokkan!\n")

✅ Semua course berhasil dikelompokkan!

In [54]:
print("=== DETAIL MAPPING ===")
detail = df.groupby('Course_group')['Course_clean'].apply(lambda x: sorted(x.unique())).reset_index()
for _, row in detail.iterrows():
    print(f"\n  [{row['Course_group']}]")
    for c in row['Course_clean']:
        print(f"    - {c}")
 
print("\n=== DISTRIBUSI FINAL ===")
dist = df['Course_group'].value_counts()
for group, count in dist.items():
    bar = '█' * count
    pct = count / len(df) * 100
    print(f"  {group:<25} {count:>3} ({pct:4.1f}%)  {bar}")

=== DETAIL MAPPING ===

  [Business & Economics]
    - Accounting
    - Banking Studies
    - Business Administration
    - Economics

  [Other]
    - Other

  [STEM]
    - BCS
    - BIT
    - Biomedical Science
    - Biotechnology
    - Engineering
    - Marine Science
    - Mathematics

  [Social & Humanities]
    - Communication
    - English Language
    - Human Sciences
    - Islamic Education
    - Law
    - Nursing
    - Psychology
    - Radiography

=== DISTRIBUSI FINAL ===
  STEM                       63 (62.4%)  ███████████████████████████████████████████████████████████████
  Social & Humanities        31 (30.7%)  ███████████████████████████████
  Business & Economics        6 ( 5.9%)  ██████
  Other                       1 ( 1.0%)  █

In [55]:
# ── Step 6: Cross-check dengan Risk Level ────────────────────────────────────
def risk_level(row):
    score = (row['Depression']=='Yes') + (row['Anxiety']=='Yes') + (row['Panic']=='Yes')
    if score == 0: return 'Low'
    elif score == 1: return 'Medium'
    else: return 'High'
    
df['Risk_Level'] = df.apply(risk_level, axis=1)
 
print("\n=== RISK LEVEL per RUMPUN ===")
ct = pd.crosstab(df['Course_group'], df['Risk_Level'])
ct['Total'] = ct.sum(axis=1)
ct['High%'] = (ct.get('High', 0) / ct['Total'] * 100).round(1)
print(ct.to_string())

=== RISK LEVEL per RUMPUN ===
Risk_Level            High  Low  Medium  Total  High%
Course_group
Business & Economics     2    3       1      6   33.3
Other                    0    0       1      1    0.0
STEM                    16   23      24     63   25.4
Social & Humanities     10   11      10     31   32.3

In [56]:
df

,Gender,Age,Course,Year,CGPA,Marital,Depression,Anxiety,Panic,Treatment,Course_clean,Course_group,Risk_Level
0,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No,Engineering,STEM,High
1,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No,Islamic Education,Social & Humanities,Medium
2,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No,BIT,STEM,High
3,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No,Law,Social & Humanities,Medium
4,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No,Mathematics,STEM,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No,BCS,STEM,Medium
97,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No,Engineering,STEM,High
98,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No,Nursing,Social & Humanities,High
99,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No,Islamic Education,Social & Humanities,Low
100,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No,Biomedical Science,STEM,Low

In [57]:
df.drop('Course', axis=1, inplace=True)
df.rename(columns={'Course_clean': 'Course'}, inplace=True)

In [58]:
df

,Gender,Age,Year,CGPA,Marital,Depression,Anxiety,Panic,Treatment,Course,Course_group,Risk_Level
0,Female,18.0,year 1,3.00 - 3.49,No,Yes,No,Yes,No,Engineering,STEM,High
1,Male,21.0,year 2,3.00 - 3.49,No,No,Yes,No,No,Islamic Education,Social & Humanities,Medium
2,Male,19.0,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No,BIT,STEM,High
3,Female,22.0,year 3,3.00 - 3.49,Yes,Yes,No,No,No,Law,Social & Humanities,Medium
4,Male,23.0,year 4,3.00 - 3.49,No,No,No,No,No,Mathematics,STEM,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
96,Female,21.0,year 1,3.50 - 4.00,No,No,Yes,No,No,BCS,STEM,Medium
97,Male,18.0,Year 2,3.00 - 3.49,No,Yes,Yes,No,No,Engineering,STEM,High
98,Female,19.0,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No,Nursing,Social & Humanities,High
99,Female,23.0,year 4,3.50 - 4.00,No,No,No,No,No,Islamic Education,Social & Humanities,Low
100,Male,20.0,Year 2,3.00 - 3.49,No,No,No,No,No,Biomedical Science,STEM,Low